gui:
    theme:
      activeBorderColor:
      - '#bd93f9'
      - bold
      inactiveBorderColor:
      - '#6272a4'
      searchingActiveBorderColor:
      - '#ffb86c'
      optionsTextColor:
      - '#bd93f9'
      selectedLineBgColor:
      - '#44475a'
      cherryPickedCommitBgColor:
      - '#6272a4'
      cherryPickedCommitFgColor:
      - '#bd93f9'
      markedBaseCommitFgColor:
      - '#bd93f9'
      unstagedChangesColor:
      - '#ff5555'
      defaultFgColor:
      - '#f8f8f2'
os:
    editPreset: nvim
