default-scheme = "base16-tokyo-night-storm"

# 1. Ghostty
[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-terminal"
themes-dir = "themes/ghostty"
hook = """
mkdir -p ~/.config/ghostty/themes
command cp -f "$TINTY_THEME_FILE_PATH" ~/.config/ghostty/themes/tinted-theming
killall -SIGUSR2 ghostty 2>/dev/null || true
"""
supported-systems = ["base16", "base24"]

# 2. Tmux
[[items]]
path = "https://github.com/tinted-theming/tinted-tmux"
name = "tinted-tmux"
themes-dir = "colors"
hook = """
tmux source-file %f
"""

# 3. Lazygit
[[items]]
path = "https://github.com/tinted-theming/tinted-lazygit"
name = "tinted-lazygit"
themes-dir = "themes"
supported-systems = ["base16"]

# 4. Neovim, Nushell
[[items]]
path = "https://github.com/tinted-theming/tinted-nvim"
name = "tinted-nvim"
themes-dir = "colors"
supported-systems = ["base16", "base24"]
hook = """
command cp -f %f ~/.config/nvim/colors
nu ~/.config/tinted-theming/tinty/palette.nu
"""

