[mgr]
ratio = [1, 4, 3]
sort_dir_first = true
show_symlink = false
linemode = "mtime"

[preview]
wrap = "yes"
max_width = 1000
max_height = 1500

[tasks]
image_bound = [10000, 10000]

[opener]
edit = [{ run = 'nvim "$@"', block = true, desc = "nvim" }]
# subl = [{ run = 'subl "$@"', desc = "subl" }]

