# OPTIONS
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on
set -g status-position top
set -g status-interval 3
set -g set-clipboard on
set -g detach-on-destroy off
set -g mode-keys vi
set -g status-keys vi
set -g mouse on
set -g history-limit 10000
set -g repeat-time 1000
set-option -g default-command "/opt/homebrew/bin/nu"
set-option -g default-shell "/opt/homebrew/bin/nu"
set-option -g focus-events on

# PREFIX
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# RELOAD CONFIG
bind r source-file "~/.tmux.conf" \; display "tmux Reloaded"

# SPLIT PANES / CREATE WINDOW
unbind '"'
unbind %
unbind &
bind b split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# MOVE TO PANE
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

# RESIZE PANES
unbind C-Left
unbind C-Right
unbind C-Up
unbind C-Down
unbind M-Left
unbind M-Right
unbind M-Up
unbind M-Down
unbind S-Left
unbind S-Right
unbind S-Up
unbind S-Down
bind-key -r -T prefix       C-Up              resize-pane -U 5
bind-key -r -T prefix       C-Down            resize-pane -D 5
bind-key -r -T prefix       C-Left            resize-pane -L 5
bind-key -r -T prefix       C-Right           resize-pane -R 5

# SESSIONX
unbind o
set -g @sessionx-bind "o"
set -g @sessionx-filter-current "false"
set -g @sessionx-tree-mode "true"
set -g @sessionx-pointer "▶ "

# COPY AS IN NVIM
bind-key -T copy-mode-vi "v" send -X begin-selection
bind -T copy-mode-vi "y" send-keys -X copy-pipe-and-cancel "pbcopy"
unbind -T copy-mode-vi MouseDragEnd1Pane

# COLORS
set -g status-left "#[fg=#806c61]  #S"
# set -g window-status-current-format "#[bold]  #I:#W"
# set -g window-status-format " #I:#W"
set -g window-status-current-format "#[italics, fg=#f28171] #I #[bold, noitalics] #W"
set -g window-status-format " #I #W"
set -g status-right "#{nowplaying} |   #{cpu} |   #{mem} |   %H:%M "
set -g status-justify centre
set -g status-left-length 200
set -g status-right-length 200
set -g window-status-current-style bg=default
set -g window-status-style bg=default

# PLUGINS
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "hendrikmi/tmux-cpu-mem-monitor"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin "barlevalon/tmux-nowplaying-macos"
set -g @resurrect-strategy-nvim "session"
set -g @resurrect-capture-pane-contents "on"
set -g @continuum-restore "on"
run "~/.tmux/plugins/tpm/tpm"
